server {
    listen 80;

    location /mini-kafka/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /mini-kafka/index.html;
    }

    location = / {
        return 301 /mini-kafka/;
    }
}
